- hosts: web
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
        update_cache: yes
        cache_valid_time: 3600
        
  - name: "install nginx"
    apt:
       name: ['nginix']
       state: latest
       
  -name: "create www directory"
   file:
      path: /var/www/{{ domain }}
      state: directory
      mode: '0775'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      
  -name:  delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx
    
  -name: copy nginx site.conf
    template:
      src: site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: '0644'
    notify: restart nginx
    
  handlers:
    -name: persist
     shell: "systemctl daemon-reload"
     when: "{{ have_systemd.stdout == 'true' }}"
    
  handlers:
    -name: restart nginix
     service:
      name: nginix
      state: restarted